name: Build DOCX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install docx

      - name: Run script
        run: node doc_completo.js

      - name: Upload DOCX
        uses: actions/upload-artifact@v4
        with:
          name: documento-docx
          path: "*.docx"
