name: Build DOCX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install docx

      - name: Run script
        run: node doc_completo.js

      - name: Upload DOCX artifact
        uses: actions/upload-artifact@v4
        with:
          name: documento-docx
          path: "*.docx"
